import type { DocumentMetadata, InductionField } from "@/types/induction";

export const documentMetadata: DocumentMetadata = {
  code: "UHSF16.01",
  title: "SITE INDUCTION REGISTRATION FORM",
  issued: "08.11.2022",
  documentType: "FORM",
  documentCreatedBy: "HSEQ Dept",
  status: "APPROVED",
  page: "1 of 1",
};

export const sectionLabels = {
  personal: {
    title: "Inductee Personal Details",
    subtitle: "To be completed by the inductee",
  },
  competence: {
    title: "Competence and Training",
    subtitle: "To be completed by the inductee",
  },
  declaration: {
    title: "Safe Working Declaration",
    subtitle: "To be completed by the inductee",
  },
  acknowledgement: {
    title: "Acknowledgement — Uplands Inductor",
    subtitle: "To be completed by Uplands Inductor",
  },
} as const;

export const uhsf1601Schema: InductionField[] = [
  {
    id: "fullName",
    section: "personal",
    label: "Full name",
    originalLabel: "FULL NAME",
    type: "text",
    role: "inductee",
    allowSkip: true,
    placeholder: "Enter your full name",
  },
  {
    id: "contactNumber",
    section: "personal",
    label: "Contact number",
    originalLabel: "CONTACT NUMBER",
    type: "phone",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "homeAddress",
    section: "personal",
    label: "Home address",
    originalLabel: "HOME ADDRESS",
    type: "address",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "companyName",
    section: "personal",
    label: "Company name",
    originalLabel: "COMPANY NAME",
    type: "text",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "occupation",
    section: "personal",
    label: "Occupation",
    originalLabel: "OCCUPATION",
    description: "Examples: Electrician, Carpenter, Site Manager, Labourer.",
    type: "text",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "emergencyContactName",
    section: "personal",
    label: "Name of emergency contact",
    originalLabel: "NAME OF EMERGENCY CONTACT",
    type: "text",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "emergencyContactTelephone",
    section: "personal",
    label: "Emergency contact telephone number",
    originalLabel: "EMERGENCY CONTACT TELEPHONE NUMBER",
    type: "phone",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "medicalInformation",
    section: "personal",
    label: "Do you wish to provide any information about a medical condition or prescription medication that may affect your safety when on site?",
    originalLabel: "PLEASE INFORM US ABOUT ANY MEDICAL CONDITION YOU MAY HAVE OR PRESCRIPTION MEDICATION YOU ARE TAKING THAT MAY AFFECT YOUR SAFETY WHEN ON SITE*",
    description: "This information is requested on a voluntary basis. The information you provide is understood to be confidential and is kept securely on site.",
    type: "medical",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "competenceIntro",
    section: "competence",
    label: "Competence and Training",
    description: "We now need to record your relevant cards, qualifications and training.",
    type: "information",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "cscsCardNumber",
    section: "competence",
    label: "What is your valid CSCS card number?",
    originalLabel: "VALID CSCS CARD NUMBER",
    type: "text",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "cscsExpiry",
    section: "competence",
    label: "When does your CSCS card expire?",
    originalLabel: "CSCS EXPIRY",
    type: "date",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "asbestosAwarenessCertificate",
    section: "competence",
    label: "Do you have a valid Asbestos Awareness certificate?",
    originalLabel: "VALID ASBESTOS AWARENESS CERTIFICATE (TICK IF PRESENT)",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "erectScaffolding",
    section: "competence",
    label: "Are you going to erect scaffolding?",
    originalLabel: "ARE YOU GOING TO ERECT SCAFFOLDING? (YES / NO)",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "cisrsNumber",
    section: "competence",
    label: "What is your CISRS number?",
    originalLabel: "CISRS NO (IF APPLICABLE)",
    type: "text",
    role: "inductee",
    allowSkip: true,
    conditional: { field: "erectScaffolding", equals: "Yes" },
    autoNotApplicableWhen: [{ field: "erectScaffolding", equals: "No", reason: "Scaffolding not being erected" }],
  },
  {
    id: "cisrsExpiryDate",
    section: "competence",
    label: "When does your CISRS qualification/card expire?",
    originalLabel: "EXPIRY DATE (IF APPLICABLE)",
    type: "date",
    role: "inductee",
    allowSkip: true,
    conditional: { field: "erectScaffolding", equals: "Yes" },
    autoNotApplicableWhen: [{ field: "erectScaffolding", equals: "No", reason: "Scaffolding not being erected" }],
  },
  {
    id: "operatePlant",
    section: "competence",
    label: "Are you going to operate plant?",
    originalLabel: "ARE YOU GOING TO OPERATE PLANT? (YES / NO)",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "cpcsNumber",
    section: "competence",
    label: "What is your CPCS number?",
    originalLabel: "CPCS NO (IF APPLICABLE)",
    type: "text",
    role: "inductee",
    allowSkip: true,
    conditional: { field: "operatePlant", equals: "Yes" },
    autoNotApplicableWhen: [{ field: "operatePlant", equals: "No", reason: "Plant not being operated" }],
  },
  {
    id: "cpcsExpiryDate",
    section: "competence",
    label: "When does your CPCS qualification/card expire?",
    originalLabel: "EXPIRY DATE (IF APPLICABLE)",
    type: "date",
    role: "inductee",
    allowSkip: true,
    conditional: { field: "operatePlant", equals: "Yes" },
    autoNotApplicableWhen: [{ field: "operatePlant", equals: "No", reason: "Plant not being operated" }],
  },
  {
    id: "clientSpecificTraining",
    section: "competence",
    label: "Client specific training",
    originalLabel: "CLIENT SPECIFIC TRAINING [Tesco Academy, M&S Academy etc]",
    description: "For example: Tesco Academy, M&S Academy etc.",
    type: "text",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "clientTrainingCompletionDate",
    section: "competence",
    label: "When did you complete this client-specific training?",
    originalLabel: "COMPLETION DATE",
    type: "date",
    role: "inductee",
    allowSkip: true,
    conditional: { field: "clientSpecificTraining", hasValue: true },
    autoNotApplicableWhen: [
      { field: "clientSpecificTraining", skipped: true, reason: "Client specific training not provided" },
    ],
  },
  {
    id: "clientTrainingExpiryDate",
    section: "competence",
    label: "When does this client-specific training expire?",
    originalLabel: "EXPIRY DATE",
    type: "date",
    role: "inductee",
    allowSkip: true,
    conditional: { field: "clientSpecificTraining", hasValue: true },
    autoNotApplicableWhen: [
      { field: "clientSpecificTraining", skipped: true, reason: "Client specific training not provided" },
    ],
  },
  {
    id: "trainedFirstAider",
    section: "competence",
    label: "Are you a trained First Aider?",
    originalLabel: "ARE YOU A TRAINED FIRST AIDER? (YES / NO)",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "trainedFireWarden",
    section: "competence",
    label: "Are you a trained Fire Warden?",
    originalLabel: "ARE YOU A TRAINED FIRE WARDEN? (YES / NO)",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "supervisor",
    section: "competence",
    label: "Are you a Supervisor?",
    originalLabel: "ARE YOU A SUPERVISOR? (YES / NO)",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "smstsSssts",
    section: "competence",
    label: "Do you hold a current SMSTS or SSSTS?",
    originalLabel: "DO YOU HOLD A CURRENT SMSTS OR SSSTS? (YES / NO)",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "ramsBriefing",
    section: "competence",
    label: "Has your employer briefed you on your Risk Assessment and Method Statement?",
    originalLabel: "HAS YOUR EMPLOYER BRIEFED YOU ON YOUR RISK ASSESSMENT AND METHOD STATEMENT? (YES / NO)",
    warning: "Important: No One Is Permitted to Commence Work Without a Briefing on Their Risk Assessment and Method Statement",
    type: "yes-no",
    group: "competence-checklist",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "cscsUpload",
    section: "competence",
    label: "Upload your CSCS card",
    description: "Take or upload a clear photo of your CSCS card.",
    type: "upload",
    group: "document-uploads",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "asbestosAwarenessUpload",
    section: "competence",
    label: "Upload your Asbestos Awareness certificate",
    description: "Take or upload a photo of your valid Asbestos Awareness certificate.",
    type: "upload",
    group: "document-uploads",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "manualHandlingUpload",
    section: "competence",
    label: "Upload your Manual Handling Awareness certificate",
    description: "Take or upload a photo of your Manual Handling Awareness certificate.",
    type: "upload",
    group: "document-uploads",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "ramsDeclaration",
    section: "declaration",
    group: "declaration-group",
    label: "I CONFIRM THAT I HAVE READ AND UNDERSTAND THE RISK ASSESSMENTS AND METHOD STATEMENTS PROVIDED BY MY EMPLOYER AND I WILL ADHERE TO THEM AT ALL TIMES.",
    type: "declaration",
    role: "inductee",
    allowSkip: true,
    confirmLabel: "I confirm",
  },
  {
    id: "siteRulesDeclaration",
    section: "declaration",
    group: "declaration-group",
    label: "I AGREE TO ABIDE BY THE SITE RULES DISCUSSED AT THE SITE INDUCTION.",
    type: "declaration",
    role: "inductee",
    allowSkip: true,
    confirmLabel: "I agree",
  },
  {
    id: "ppeDeclaration",
    section: "declaration",
    group: "declaration-group",
    label: "I AGREE TO WEAR THE PPE STATED IN THE INDUCTION DURING MY TIME ON SITE.",
    type: "declaration",
    role: "inductee",
    allowSkip: true,
    confirmLabel: "I agree",
  },
  {
    id: "inducteeSignature",
    section: "declaration",
    group: "declaration-group",
    label: "Signed",
    originalLabel: "SIGNED",
    type: "signature",
    role: "inductee",
    allowSkip: true,
  },
  {
    id: "declarationDate",
    section: "declaration",
    group: "declaration-group",
    label: "Date",
    originalLabel: "DATE",
    type: "date",
    role: "inductee",
    allowSkip: true,
    defaultToday: true,
  },
  {
    id: "inducteeComplete",
    section: "acknowledgement",
    label: "Inductee section complete",
    description: "The next section is to be completed by the Uplands Inductor.",
    type: "information",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "siteName",
    section: "acknowledgement",
    label: "Site Name",
    originalLabel: "Site Name",
    type: "text",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ppeIntro",
    section: "acknowledgement",
    label: "Please confirm which PPE is present.",
    description: "The original sheet says TICK IF PRESENT.",
    type: "information",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ppeHardHat",
    section: "acknowledgement",
    label: "Hard Hat",
    originalLabel: "HARD HAT",
    type: "presence",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ppeHighVisibilityVest",
    section: "acknowledgement",
    label: "High Visibility Vest",
    originalLabel: "HIGH VISIBILITY VEST",
    note: "In accordance with the clients spec.",
    type: "presence",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ppeGloves",
    section: "acknowledgement",
    label: "Gloves",
    originalLabel: "GLOVES",
    note: "Appropriate to the task.",
    type: "presence",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ppeBoots",
    section: "acknowledgement",
    label: "Boots",
    originalLabel: "BOOTS",
    note: "With midsoles.",
    type: "presence",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ppeSafetyEyewear",
    section: "acknowledgement",
    label: "Safety Eyewear",
    originalLabel: "SAFETY EYEWEAR",
    note: "In accordance with the clients' standards.",
    type: "presence",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ppeRpe",
    section: "acknowledgement",
    label: "RPE",
    originalLabel: "RPE",
    note: "Appropriate and face fitted.",
    type: "presence",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "inductorName",
    section: "acknowledgement",
    label: "Inductor name",
    originalLabel: "INDUCTOR NAME & DATE",
    type: "text",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "inductionDate",
    section: "acknowledgement",
    label: "Induction date",
    originalLabel: "INDUCTOR NAME & DATE",
    type: "date",
    role: "inductor",
    allowSkip: true,
    defaultToday: true,
  },
  {
    id: "inductorSignature",
    section: "acknowledgement",
    label: "Inductor sign",
    originalLabel: "INDUCTOR SIGN",
    type: "signature",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "inductorJobTitle",
    section: "acknowledgement",
    label: "Inductor job title",
    originalLabel: "INDUCTOR JOB TITLE",
    type: "text",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "copiesIntro",
    section: "acknowledgement",
    label: "Copies taken",
    description: "Tick the documents for which a copy has been taken.",
    type: "information",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "cscsCopy",
    section: "acknowledgement",
    label: "CSCS",
    originalLabel: "CSCS (TICK IF COPY TAKEN)",
    type: "copy-status",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "aaCertCopy",
    section: "acknowledgement",
    label: "Asbestos Awareness Certificate — copy taken",
    originalLabel: "AA CERT (TICK IF COPY TAKEN)",
    type: "copy-status",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "ipafCopy",
    section: "acknowledgement",
    label: "IPAF",
    originalLabel: "IPAF (TICK IF COPY TAKEN)",
    type: "copy-status",
    role: "inductor",
    allowSkip: true,
  },
  {
    id: "spaCopy",
    section: "acknowledgement",
    label: "SPA",
    originalLabel: "SPA (TICK IF COPY TAKEN)",
    type: "copy-status",
    role: "inductor",
    allowSkip: true,
  },
];
